#!/bin/sh

# Written with pandoc 2.14.2

# usage:
# - `./render.sh proposal.md html` produces a HTML version of proposal.md

cd "$(dirname "$0")"
basename=$(basename "$1" .md)
extension=${2:-pdf} # uses pdf as the default extension
bib=${3:-"../references/imf.bib"}
bib=$(readlink -f $bib) # get full path
csl=$(readlink -f \
../references/chicago-fullnote-bibliography-short-title-subsequent.csl)
# csl=$(readlink -f ../references/chicago-note-bibliography-with-ibid.csl)

if [[ $basename = "index" ]];
then
  basename="thesis"
fi

cd $(dirname $1)
pandoc -V geometry:margin=1.5in \
  -f markdown \
  -o "$basename.$extension" \
  --bibliography=$bib \
  --csl=$csl \
  --filter pandoc-include \
  --citeproc \
  -V mainfont="Koreamond" \
  -V mainfontoptions="BoldFont=*-Regular" \
  -V fontsize=12pt \
  --pdf-engine=xelatex \
  $(basename $1)

echo "file render for $basename finished"
